//
// Created by Josh aka Bae on 21/03/2016.
//

#include <symbolicc++.h>

#ifndef GRAPHDRAWINGTESTS_READEQUATION_H
#define GRAPHDRAWINGTESTS_READEQUATION_H


#endif //GRAPHDRAWINGTESTS_READEQUATION_H
